package io.github.theballwizards;

import edu.princeton.cs.algs4.Digraph;

public class GraphBuilder {
    public static final String GRAPH_FILEPATH = "src/main/resources/graph.txt";

    /**
     * Builds a directional graph of urls from either web scraping or a saved cache file
     * @return A directional graph or urls
     */
    public static Digraph build() {
        if (hasCachedDataFile()) {
            final String graphData = readGraphDataFromFile();
            return generateGraphFromUrlsEdgeList(graphData);
        }
        else {
            final String graphData = WebScraper.scrapeEdgeListOfUrls();
            return generateGraphFromUrlsEdgeList(graphData);
        }
    }

    /**
     * Generates a directional graph of urls from an edge list.
     * Edge list should be generated by WebScraper.
     * @param edgeList Edge list of urls, separated by spaces and newlines.
     * @return A directional graph of urls.
     */
    private static Digraph generateGraphFromUrlsEdgeList(String edgeList) {
        return null; //TODO
    }

    /**
     * Checks if there is cached graph data and if it is valid.
     */
    private static boolean hasCachedDataFile() {
        return false; //TODO
    }

    /**
     * Reads potentially saved graph data from the cache file.
     * Check with hasCachedDataFile before using.
     * @return An edge list of urls
     */
    private static String readGraphDataFromFile() {
        return null; //TODO
    }

}
